[package]
name = "vdash"
description = "SAFE Network Vault Dashboard"
version = "0.2.0"
authors = ["Mark <git@happybeing.com>"]
license = "GPL-3.0"
homepage = "https://github.com/theWebalyst/vdash"
repository = "https://github.com/theWebalyst/vdash"
readme = "README.md"
exclude = [".github"]
keywords = ["utility", "logfile", "monitor", "cli", "safenetwork"]
categories = ["command-line-utilities"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["termion"]

[dependencies]
rand = "0.7.3"
structopt = "~0.3.15"
tokio = "0.2.22"
futures = "0.3.5"
linemux = "0.1.1"
tui = { version = "0.11.0", features = ["termion", "crossterm"], default-features = false }
termion = { version = "1.5", optional = true }
crossterm = { version = "0.17", optional = true }
regex = "1.3.9"
tempfile = "3.1.0"
time = "0.2.16"
lazy_static = "1.4.0"
chrono = "0.4.15"
log = "0.4.11"
env_logger = "0.7.1"
#unicode-segmentation = "1.2"
#unicode-width = "0.1"

[[bin]]
name = "vdash"
required-features = ["termion"]
path = "src/bin/logtail-termion.rs"

[[bin]]
name = "vdash-crossterm"
required-features = ["crossterm"]
path = "src/bin/logtail-crossterm.rs"
