[package]
name = "logtail"
description = "Displays and updates a dashboard based on one or more logfiles"
version = "0.1.0"
authors = ["Mark <git@happybeing.com>"]
license = "GPLv3"
homepage = "https://github.com/imsnif/bandwhich"
repository = "https://github.com/imsnif/bandwhich"
readme = "README.md"
keywords = ["utility", "logfile", "monitor", "cli"]
categories = ["command-line-utilities"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
structopt = "~0.3.15"
termion = "1.5.5"
tui = "0.10.0"
linemux = "0.1.1"
tokio = "0.2.22"
futures = "0.3.5"
