[package]
name = "safe-dash"
version = "0.1.0"
authors = ["Mark <git@happybeing.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
structopt = "~0.3.15"
termion = "1.5.5"
tui = "0.10.0"
util = "0.1.2"  